#spring:
#  cloud:
#    discovery:
#      enabled: true
eureka:
  instance:
    secure-port: 8443  # Advertise HTTPS port
    secure-port-enabled: true
    non-secure-port-enabled: false

logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.web.client: DEBUG
    org.apache.http: DEBUG