#spring:
#  cloud:
#    discovery:
#      enabled: true
eureka:
  instance:
    secure-port: 8444  # Advertise HTTPS port
    secure-port-enabled: true
    non-secure-port-enabled: false
    metadata-map:
      management.port: 8444
      management.secure: true

#logging:
#  level:
#    org.springframework.cloud: DEBUG
#    org.springframework.web.client: DEBUG
#    org.apache.http: DEBUG